Repository github/codeql-go, pull requests merged in 2020-05, with the labels that each got.

#126 Switch to new-style change notes.
  change-notes/1.25/analysis-go.md
  change-notes/1.25/extractor-go.md
  change-notes/2020-05-01-bad-redirect-check.md
  change-notes/2020-05-01-macaron-model.md
Labels: has-change-note

#128 Add support for Mux library
  change-notes/2020-05-05-mux-model.md
  ql/src/go.qll
  ql/src/semmle/go/frameworks/Mux.qll
  ql/test/library-tests/semmle/go/frameworks/Mux/UntrustedFlowSources.expected
  ql/test/library-tests/semmle/go/frameworks/Mux/UntrustedFlowSources.ql
  ql/test/library-tests/semmle/go/frameworks/Mux/go.mod
  ql/test/library-tests/semmle/go/frameworks/Mux/mux.go
  ql/test/library-tests/semmle/go/frameworks/Mux/vendor/github.com/gorilla/mux/LICENSE
  ql/test/library-tests/semmle/go/frameworks/Mux/vendor/github.com/gorilla/mux/stub.go
  ql/test/library-tests/semmle/go/frameworks/Mux/vendor/modules.txt
Labels: has-change-note

#62 Port recent data-flow improvements
  change-notes/2020-05-07-update-data-flow.md
  ql/src/semmle/go/dataflow/internal/DataFlowImpl.qll
  ql/src/semmle/go/dataflow/internal/DataFlowImplCommon.qll
  ql/test/query-tests/Security/CWE-089/SqlInjection.expected
Labels: has-change-note

#117 Add experimental library: gin web framework
  ql/src/experimental/frameworks/Gin.qll
  ql/test/experimental/frameworks/Gin/Gin.expected
  ql/test/experimental/frameworks/Gin/Gin.go
  ql/test/experimental/frameworks/Gin/Gin.ql
  ql/test/experimental/frameworks/Gin/go.mod
  ql/test/experimental/frameworks/Gin/vendor/github.com/gin-gonic/gin/LICENSE
  ql/test/experimental/frameworks/Gin/vendor/github.com/gin-gonic/gin/binding/stub.go
  ql/test/experimental/frameworks/Gin/vendor/github.com/gin-gonic/gin/stub.go
  ql/test/experimental/frameworks/Gin/vendor/modules.txt
Labels: no-change-note-required

#130 Golang : Add MongoDB injection support
  ql/src/go.qll
  ql/src/semmle/go/frameworks/NoSQL.qll
  ql/src/semmle/go/security/SqlInjection.qll
  ql/src/semmle/go/security/SqlInjectionCustomizations.qll
  ql/test/library-tests/semmle/go/frameworks/NoSQL/QueryString.expected
  ql/test/library-tests/semmle/go/frameworks/NoSQL/QueryString.ql
  ql/test/library-tests/semmle/go/frameworks/NoSQL/go.mod
  ql/test/library-tests/semmle/go/frameworks/NoSQL/main.go
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/go.mongodb.org/mongo-driver/LICENSE
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/go.mongodb.org/mongo-driver/bson/primitive/stub.go
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/go.mongodb.org/mongo-driver/bson/stub.go
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/modules.txt
  ql/test/query-tests/Security/CWE-089/SqlInjection.expected
  ql/test/query-tests/Security/CWE-089/go.mod
  ql/test/query-tests/Security/CWE-089/mongoDB.go
  ql/test/query-tests/Security/CWE-089/vendor/github.com/Masterminds/squirrel/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/LICENSE
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/bson/primitive/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/bson/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/options/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/modules.txt
Labels: needs-polishing

#139 Cleanup of `io` model
  change-notes/2020-05-13-io-model.md
  ql/src/semmle/go/frameworks/Stdlib.qll
Labels: has-change-note

#138 Fix frontend errors in two tests and a code example
  ql/src/experimental/CWE-807/SensitiveConditionBypassBad.go
  ql/src/semmle/go/frameworks/NoSQL.qll
  ql/test/library-tests/semmle/go/frameworks/NoSQL/main.go
  ql/test/query-tests/Security/CWE-022/tst.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
Labels: no-change-note-required

#140 Update dependency stubs
  ql/test/library-tests/semmle/go/frameworks/Email/go.mod
  ql/test/library-tests/semmle/go/frameworks/Email/vendor/modules.txt
  ql/test/library-tests/semmle/go/frameworks/NoSQL/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
  ql/test/library-tests/semmle/go/frameworks/SQL/go.mod
  ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/Masterminds/squirrel/stub.go
  ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/go-pg/pg/orm/stub.go
  ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/go-pg/pg/stub.go
  ql/test/library-tests/semmle/go/frameworks/SQL/vendor/github.com/go-pg/pg/v9/stub.go
  ql/test/library-tests/semmle/go/frameworks/SystemCommandExecutors/go.mod
  ql/test/library-tests/semmle/go/frameworks/SystemCommandExecutors/vendor/modules.txt
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/options/stub.go
  ql/test/query-tests/Security/CWE-089/vendor/go.mongodb.org/mongo-driver/mongo/stub.go
  ql/test/query-tests/Security/CWE-312/go.mod
  ql/test/query-tests/Security/CWE-312/vendor/modules.txt
  ql/test/query-tests/Security/CWE-643/go.mod
  ql/test/query-tests/Security/CWE-643/vendor/github.com/ChrisTrenkamp/goxpath/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/ChrisTrenkamp/goxpath/tree/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/antchfx/htmlquery/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/antchfx/jsonquery/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/antchfx/xmlquery/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/antchfx/xpath/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/go-xmlpath/xmlpath/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/jbowtie/gokogiri/xml/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/jbowtie/gokogiri/xpath/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/github.com/santhosh-tekuri/xpathparser/stub.go
  ql/test/query-tests/Security/CWE-643/vendor/modules.txt
  ql/test/query-tests/filters/ClassifyFiles/go.mod
  ql/test/query-tests/filters/ClassifyFiles/vendor/modules.txt
Labels: no-change-note-required

#141 ReflectedXss improvements
  change-notes/2020-05-11-reflected-xss.md
  ql/src/Security/CWE-601/BadRedirectCheck.ql
  ql/src/semmle/go/Concepts.qll
  ql/src/semmle/go/dataflow/SSA.qll
  ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
  ql/src/semmle/go/frameworks/HTTP.qll
  ql/src/semmle/go/frameworks/Macaron.qll
  ql/src/semmle/go/frameworks/Stdlib.qll
  ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
  ql/src/semmle/go/security/ReflectedXssCustomizations.qll
  ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
  ql/test/query-tests/Security/CWE-079/tst.go
Labels: has-change-note

#143 Clarify which types have a qualified name.
  ql/src/semmle/go/Types.qll
Labels: no-change-note-required

#144 Refine `Method.implements` so that interface methods only implement themselves.
  ql/src/semmle/go/Scopes.qll
  ql/test/library-tests/semmle/go/Scopes/DeclaredEntity.expected
  ql/test/library-tests/semmle/go/Scopes/EntityReference.expected
  ql/test/library-tests/semmle/go/Scopes/EntityType.expected
  ql/test/library-tests/semmle/go/Scopes/MethodImplements.expected
  ql/test/library-tests/semmle/go/Scopes/MethodImplements.ql
  ql/test/library-tests/semmle/go/Scopes/MethodImplementsName.expected
  ql/test/library-tests/semmle/go/Scopes/MethodImplementsName.ql
  ql/test/library-tests/semmle/go/Scopes/Methods.expected
  ql/test/library-tests/semmle/go/Scopes/TypeImplements.expected
  ql/test/library-tests/semmle/go/Scopes/types.go
  ql/test/query-tests/Security/CWE-079/ReflectedXss.expected
  ql/test/query-tests/Security/CWE-079/tst.go
Labels: no-change-note-required

#145 Simplify logic in AllocationSizeOverflow query.
  ql/src/semmle/go/security/AllocationSizeOverflowCustomizations.qll
Labels: no-change-note-required

#149 Clean up NoSQL library
  change-notes/2020-05-20-mongodb-model.md
  ql/src/semmle/go/frameworks/NoSQL.qll
  ql/src/semmle/go/security/SqlInjection.qll
  ql/src/semmle/go/security/SqlInjectionCustomizations.qll
  ql/test/library-tests/semmle/go/frameworks/NoSQL/Query.expected
  ql/test/library-tests/semmle/go/frameworks/NoSQL/Query.ql
  ql/test/library-tests/semmle/go/frameworks/NoSQL/QueryString.ql
Labels: has-change-note

#152 Link README.md to the CodeQL repo
  README.md
Labels: documentation

#161 Broaden definition of mutable types for taint tracking
  ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.ql
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getEntryNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/reset.go
Labels: no-change-note-required

#162 Consider `Request.FormValue(...)` as a source for URL redirects.
  change-notes/2020-05-29-open-redirect.md
  ql/src/semmle/go/security/OpenUrlRedirectCustomizations.qll
  ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/OpenUrlRedirect.expected
  ql/test/query-tests/Security/CWE-601/OpenUrlRedirect/stdlib.go
Labels: has-change-note

#157 Make FunctionOutput.isResult(0) and CallNode.getResult(0) match single results
  ql/src/experimental/frameworks/Gin.qll
  ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
  ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
  ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
  ql/src/semmle/go/frameworks/Stdlib.qll
  ql/src/semmle/go/security/ReflectedXssCustomizations.qll
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult.ql
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult_int.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_isResult_int.ql
  ql/test/library-tests/semmle/go/dataflow/Nodes/BinaryOperationNodes.expected
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode.expected
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getArgument.expected
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult.expected
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult.ql
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult_int.expected
  ql/test/library-tests/semmle/go/dataflow/Nodes/CallNode_getResult_int.ql
  ql/test/library-tests/semmle/go/dataflow/Nodes/main.go
Labels: no-change-note-required
