Repository github/codeql-go, pull requests merged in 2020-04, with the labels that each got.

#84 Docs: Move "CodeQL for Go" out of this repo
  ql/docs/learn-ql/ast.dot
  ql/docs/learn-ql/ast.png
  ql/docs/learn-ql/cfg.dot
  ql/docs/learn-ql/cfg.png
  ql/docs/learn-ql/cfg2.dot
  ql/docs/learn-ql/cfg2.png
  ql/docs/learn-ql/dfg.dot
  ql/docs/learn-ql/dfg.png
  ql/docs/learn-ql/introduce-libraries.rst
  ql/docs/learn-ql/ssa.dot
  ql/docs/learn-ql/ssa.png
Labels: documentation

#100 Add two missing change notes.
  change-notes/1.24/analysis-go.md
  change-notes/1.24/extractor-go.md
Labels: has-change-note

#106 1.24 release: finalize change notes for Go
  change-notes/1.24/analysis-go.md
  change-notes/1.24/extractor-go.md
Labels: documentation

#114 Use CodeQL version 2.1.1 for tests
  .github/workflows/codeqltest.yml
Labels: no-change-note-required

#122 Fix `getExitNode` for receiver outputs.
  ql/src/semmle/go/dataflow/FunctionInputsAndOutputs.qll
  ql/src/semmle/go/dataflow/internal/DataFlowPrivate.qll
  ql/src/semmle/go/dataflow/internal/DataFlowUtil.qll
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getEntryNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionInput_getExitNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionModelStep.ql
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/FunctionOutput_getExitNode.expected
  ql/test/library-tests/semmle/go/dataflow/FunctionInputsAndOutputs/tst.go
Labels: no-change-note-required
